version: "3"
services:
  backend:
    image: hamster-mw
    build: backend
    ports:
      - "8080:8080"
      - "5005:5005"
    environment:
      - JAVA_TOOL_OPTIONS=-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005

  frontend:
    image: hamster-fe
    build: frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend